### ISSUE TITLE
The code for UPSERT is not transactional

### ISSUE THREAD

**Issue by knz** [perimetral/deepstream.io-storage-cockroachdb#1]
Currently the adapter issues separate select/insert/update statements for the deepstream `_upsert` primitive. I believe this is bound to cause a problem if there is concurrent access to the table.

To solve this problem you can use the `UPSERT` statement that is now recognized by CockroachDB.

**Comment by perimetral** [comment]
Fixed in 1.0.2. Get new version here or on NPM.
